[project]
name = "job-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MrSinister8632", email = "yash.saxena2001@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "google-genai>=2.27.0",
    "groq>=1.7.0",
    "httpx>=0.28.1",
    "pypdf>=6.19.0",
    "pyside6>=6.11.2",
]

[project.scripts]
job-assistant = "job_assistant:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
